services:
  - type: web
    name: metagold-backend
    env: python
    buildCommand: |
      cd gold_app
      pip install -r requirements.txt
    startCommand: |
      cd gold_app && gunicorn gold_app.wsgi
    envVars:
      - key: DATABASE_URL
        value: mysql://root:oofNDzTvdDfpXMlQzTRiTOyJeWILGyDP@maglev.proxy.rlwy.net:59248/railway
    plan: free
