# Generated by Django 4.2.22 on 2025-07-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goldhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellgold',
            name='transaction',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='rupee_amount',
            new_name='inr_amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='rupee_balance',
            new_name='inr_balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='gold_price_per_gram',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gold_amount',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gold_balance',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='BuyGold',
        ),
        migrations.DeleteModel(
            name='GoldHistory',
        ),
        migrations.DeleteModel(
            name='SellGold',
        ),
    ]
