# Generated by Django 4.2.22 on 2025-08-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_buygold_user_alter_sellgold_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider_payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
